### ISSUE TITLE
Annotation value1 is recognized as a bool type and an error occurs

### ISSUE THREAD

**Issue by sekinet813** [maclof/kubernetes-client#112]
If I create the following yaml in Pod and create it, I get an error. Perhaps 1 is recognized as a bool type; no error occurred with any number other than 1.

YAML

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox-date
  annotations:
    key: 1
spec:
  containers:
    -
      name: busybox
      image: busybox
      args:
        - date
```

Error message

```
@"kind":"Status","apiVersion":"v1","metadata":[],"status":"Failure","message":"Pod in version \"v1\" cannot be handled as a 
Pod: v1.Pod.Spec: v1.PodSpec.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects \" or n, but found 1, error found in #10 byte of ...|0818b0\": 1\n |..., bigger context ...| \"key\": 1\n }\n },\n \"spec\": @\n \"container|...","reason":"BadRequest","code":400
```
