### ISSUE TITLE
Use multiple configMapRef settings

### ISSUE THREAD

**Issue by diegolima** [maclof/kubernetes-client#73]
Hello! We're trying to launch a cronjob that needs multiple `configMapRef` settings, but if we declare:
```
                     'envFrom' => [
                        'configMapRef' => 'configmap-1',
                        'configMapRef' => 'configmap-2',
                      ]
```
only the second `configMapRef` is used. How can we make it so that we have multiple entries? In the k8s YAML this works perfectly:
```
            envFrom:
              - configMapRef:
                  name: configmap-1
              - configMapRef:
                  name: configmap-2
```
